[project]
name = "back-end"
version = "0.1.0"
description = "This is the back-end for the `animize_eat` project, a platform to share anime-inspired recipes."
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "django>=6.0.1",
]
